services:
  workspace:
    image: rusterize/workspace:${RUST_VERSION}
    container_name: rusterize-workspace
    build:
      context: ./.docker/context/workspace
      args:
        RUST_VERSION: ${RUST_VERSION}
        INSTALL_WATCH: true
        INSTALL_SEA_ORM: true
        INSTALL_NUSHELL: true
    tty: true
    stdin_open: true
    volumes:
      - ./.docker/context/workspace/.config:/root/.config
      - ./.docker/target:/target
      - ${WORKSPACE_PATH}:/home
    networks:
      - default

  postgres:
    image: rusterize/postgres
    container_name: rusterize-postgres
    build:
      context: ./.docker/context/postgres
    restart: always
    shm_size: 128mb
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/data/postgres:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10

  mysql:
    image: rusterize/mysql
    container_name: rusterize-mysql
    build:
      context: ./.docker/context/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql/:rw
      - ./.docker/logs/mysql:/var/log/mysql/:rw
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 1s
      timeout: 5s
      retries: 10

networks:
  default:
    driver: bridge
    ipam:
      driver: default
