services:
#  app:
#    image: ${APP_NAME}/app
#    restart: always
#    build:
#      context: .
#      target: final
#      args:
#        RUST_VERSION: ${RUST_VERSION}
#        BIN_NAME: app
#    volumes:
#      - ./.env:/app/.env
#      - ./config:/app/config
#      - ./database:/app/database
#      - ./public:/app/public
#      - ./resources:/app/resources
#      - ./storage:/app/storage
#    ports:
#      - "8000:8000"
#    environment:
#      - RUST_LOG=debug
#    networks:
#      - default

  #  cli:
  #    image: ${APP_NAME}/cli
  #    build:
  #      context: .
  #      target: final
  #      args:
  #        RUST_VERSION: ${RUST_VERSION}
  #        BIN_NAME: cli
  #    volumes:
  #      - ./.env:/app/.env
  #      - ./config:/app/config
  #      - ./database:/app/database
  #      - ./public:/app/public
  #      - ./resources:/app/resources
  #      - ./storage:/app/storage
  #    environment:
  #      - RUST_LOG=debug

  #  postgres:
  #    image: postgres
  #    restart: always
  #    shm_size: 128mb
  #    environment:
  #      PGUSER: postgres
  #      POSTGRES_PASSWORD: example
  #    volumes:
  #      - ./.docker/data/postgres:/var/lib/postgresql/data
  #    ports:
  #      - "5432:5432"
  #    healthcheck:
  #      test: [ "CMD-SHELL", "pg_isready" ]
  #      interval: 1s
  #      timeout: 5s
  #      retries: 10

#  mysql:
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./.docker/data/mysql:/var/lib/mysql/:rw
#      - ./.docker/logs/mysql:/var/log/mysql/:rw
#    networks:
#      - default
#    healthcheck:
#      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD" ]
#      interval: 1s
#      timeout: 5s
#      retries: 10

  workspace:
    build:
      context: ./workspace
      args:
        RUST_VERSION: ${RUST_VERSION}
    tty: true
    stdin_open: true
    volumes:
      - ${WORKSPACE_PATH}:/home

networks:
  default:
    driver: bridge
    ipam:
      driver: default
