services:
  server:
    image: rust:${RUST_VERSION}
    build:
      context: .
      target: final
      args:
        RUST_VERSION: ${RUST_VERSION}
        APP_NAME: ${APP_NAME}
    ports:
      - "${APP_PORT}:8000"
    environment:
      - ADDRESS=0.0.0.0:8000
      - RUST_LOG=debug