services:
  app:
    image: ${APP_NAME:-app}:${APP_VERSION:-latest}
    container_name: ${APP_NAME:-app}
    restart: unless-stopped
    build:
      context: .
      target: final
      args:
        RUST_VERSION: ${RUST_VERSION:-1.80.1}
        BIN_NAME: ${APP_NAME:-app}
    volumes:
      - ./resources:/home/resources
      - ./database:/home/database
      - ./storage:/home/storage
    ports:
      - "8000:8000"
    command:
      - server
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "/home/app status" ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - rusterize_mysql

networks:
  rusterize_mysql:
    external: true