services:
  app:
    image: ${APP_NAME}/app
    build:
      context: .
      target: final
      args:
        RUST_VERSION: ${RUST_VERSION}
        BIN_NAME: app
    volumes:
      - ./.env:/app/.env
      - ./config:/app/config
      - ./database:/app/database
      - ./public:/app/public
      - ./resources:/app/resources
      - ./storage:/app/storage
    ports:
      - "8000:8000"
    environment:
      - RUST_LOG=debug

#  cli:
#    image: ${APP_NAME}/cli
#    build:
#      context: .
#      target: final
#      args:
#        RUST_VERSION: ${RUST_VERSION}
#        BIN_NAME: cli
#    volumes:
#      - ./.env:/app/.env
#      - ./config:/app/config
#      - ./database:/app/database
#      - ./public:/app/public
#      - ./resources:/app/resources
#      - ./storage:/app/storage
#    environment:
#      - RUST_LOG=debug

#  database:
#    image: postgres
#    restart: always
#    shm_size: 128mb
#    environment:
#      PGUSER: postgres
#      POSTGRES_PASSWORD: example
#    ports:
#      - "5432:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready" ]
#      interval: 1s
#      timeout: 5s
#      retries: 10