services:
  app:
    restart: unless-stopped
    build:
      context: .
      target: final
      args:
        RUST_VERSION: ${RUST_VERSION}
        BIN_NAME: app
    volumes:
      - ./database:/app/database
      - ./resources:/app/resources
      - ./storage:/app/storage
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - default
      - rusterize_mysql

  cli:
    build:
      context: .
      target: final
      args:
        RUST_VERSION: ${RUST_VERSION}
        BIN_NAME: cli
    volumes:
      - ./database:/app/database
      - ./resources:/app/resources
      - ./storage:/app/storage
    env_file:
      - .env
    networks:
      - rusterize_mysql

networks:
  default:
    driver: bridge
    ipam:
      driver: default
  rusterize_mysql:
    external: true